# Welcome to Jekyll! The static website generator.

title: Yigal Duppen
email: 
description: Yigal Duppen is a driven software architect
baseurl: ""  
url: "http://www.publysher.nl" 
twitter_username: "@yduppen"
github_username:  

yigal_payoff: "<span>Yigal Duppen</span> is a driven software architect"

google_analytics: 

# Build settings
markdown: kramdown

exclude: [
README.md,
Gemfile,
Gemfile.lock
]

gems:
  - octopress-autoprefixer
  - jekyll-sitemap

collections:
  projects:
    output: true
    # permalink: projects/:path/
  writings:
    output: true
    # permalink: writings/:path/

hyphenate_filter:
  language: en_uk
  left: 3
  right: 3


